# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSWeatherApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOSWeatherApp
  
  pod 'Alamofire'
  pod 'AlamofireSwiftyJSON'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'CocoaLumberjack/Swift'
  pod 'Swinject'

  target 'iOSWeatherAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSWeatherAppUITests' do
    # Pods for testing
  end

end
